default:
  image: ruby:3.1.4

stages:
  - test
  - build

services:
  - name: docker:20.10.21-dind
    command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: volume-sweeper

testing:
  stage: test
  before_script:
    - gem install bundler -v 2.3.26
    - bundle install
  script:
    - rspec
    - ./spec/support/merge.rb
  coverage: '/LOC \((\d+\.\d+%)\) covered.$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./coverage/coverage.xml
    when: always
    expire_in: "2 days"
    name: coverage
    paths:
      - ./coverage/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - when: never
  interruptible: true

build_image:
  image: docker:20.10.21
  stage: build
  variables:
    REGISTRY_HOST: REGISTRY
    IMAGE_NAME: ${REGISTRY_HOST}/${IMAGE_NAME}
    IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
    IMAGE_DIR: ./
  script:
    - apk update
    - echo "${REGISTRY_TOKEN}" | base64 -d | docker login --username ${REGISTRY_USER} --password-stdin ${REGISTRY_HOST}
    - docker build --tag ${IMAGE_NAME}:${IMAGE_TAG} $IMAGE_DIR
    - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}
    - docker push ${IMAGE_NAME}:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
